### PR TITLE
Adding Support for Arch Linux

### LINKED ISSUE #3: Need Arch Linux Support
Kindly create a support script for arch Linux.

### PR DESCRIPTION
**Pull request by ksharizard**
Closes #3 

The script works the same in installing wine, winetricks, lutris, gamemode, xanmod and winetricks dependencies. It also installs paru which helps in installing aur packages. I made this in less than a hour so I will keep this a draft for now and after a bit of polishing, it will be ready for review. Testing of the script on arch linux and its derivatives would be appreciated.

### CODE REVIEW

**Comment by ksharizard** [comment]
Script is mostly done. Just needs to be tested. Would be helpful if someone could test it on various arch-based distros and ubuntu-based distros if it works since the script gets a big overhaul.

**Comment by Loomeh** [comment]
I've tested GhoulBoii's script on my Arch install and it works perfectly. However it installs the Zen kernel instead of the Xanmod kernel. I've submitted a pull request to make the script install the Xanmod kernel via the Chaotic AUR.

**Comment by ksharizard** [comment]
I have also tested the script on arch and it worked flawlessly. Thank you @Loomeh for testing it out as well and making the needed changes.

**Comment by NayamAmarshe** [comment]
Can you please fix the merge conflicts?

**Comment by ksharizard** [comment]
> Can you please fix the merge conflicts?

Fixed.

**Pull request merged**
