### PR TITLE
Eliminate step of changing file properties.

### PR DESCRIPTION
**Pull request by Lrss**
When files are downloaded as zip or tar they preserve their file properties when extracted. So if you distribute it compressed you don't need the users to change the file properties.

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Thanks a lot for the idea. One issue though, it requires me to ship the sh file with correct permissions and it also assumes that the user would download the file from the specific given link. For these reasons, I think having universally compatible instructions would be better.

But really, thanks for the idea. I think I'm actually going to change the instructions and add a single command that the users can copy paste and execute the script in real time :D

**Comment by Lrss** [comment]
Like this? 

`wget -q -O- "https://github.com/Lrss/gameready/archive/refs/tags/Test.tar.gz" | tar -xz -C /tmp && /tmp/gameready-Test/gameready.sh`

**Comment by NayamAmarshe** [comment]
> Like this?
> 
> `wget -q -O- "https://github.com/Lrss/gameready/archive/refs/tags/Test.tar.gz" | tar -xz -C /tmp && /tmp/gameready-Test/gameready.sh`

Yes :) but we can fetch the script directly with wget though. 
`wget $url -O - | sh`

**Comment by Lrss** [comment]
Good point. Now that it is a script you expect users to use with elevated privileges, there probably should be some sort of test of its checksum to avoid MITM attacks.

**Comment by NayamAmarshe** [comment]
> Good point. Now that it is a script you expect users to use with elevated privileges, there probably should be some sort of test of its checksum to avoid MITM attacks.

Wouldn't checksum be a bit overkill for the project scope though? Since we'll be fetching the script directly from github raw link and we aren't assuming compromised devices running the script.

**Pull request merged**
